

service: appsyncmasterclass-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: dev

package: 
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies: 
          PasswordPolicy:
            MinimumLength: 8 
            RequrieLowercase: false
            RequireNumber: false
            RequireUppercase: false
            RequiredSymbols: false
          UsernameAttributes:
            - email
          Schema: 
            - AttributeDataType: String
              Name: name
              Required: false
              Mutable: true

  Outputs:
    CognitoUserPoolId:
      Value : !Ref CognitoUserPool
