

service: appsyncmasterclass-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

package: 
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}